name: CVM Pipeline for MR
trigger:
  change:
    types: [create, push]
    branches: [jdk17u-target8*]
  manual:

jobs:
  build_cvm8_fastdebug:
    name: Build CVM8 fastdebug
    image: hub.byted.org/compile/bytedance.lang.buildjdk17.multiarch:9801f8057d487c1cb6914f68a9257bdc
    timeout: 30
    steps:
      - name: Build fastdebug
        commands:
          - make -f cvm.mk cvm8default17 MODE=fastdebug
      - name: Upload artifacts
        uses: actions/upload-artifact@1.0.0
        inputs:
          name: cvm8_fastdebug
          path: cvm/build/jdk8

  build_cvm8_release:
    name: Build CVM8 release
    image: hub.byted.org/compile/bytedance.lang.buildjdk17.multiarch:9801f8057d487c1cb6914f68a9257bdc
    timeout: 30
    steps:
      - name: Build release
        commands:
          - make -f cvm.mk cvm8default17 MODE=release
      - name: Upload artifacts
        uses: actions/upload-artifact@1.0.0
        inputs:
          name: cvm8_release
          path: cvm/build/jdk8

  build_cvm8_slowdebug:
    name: Build CVM8 slowdebug
    image: hub.byted.org/compile/bytedance.lang.buildjdk17.multiarch:9801f8057d487c1cb6914f68a9257bdc
    timeout: 30
    steps:
      - name: Build slowdebug
        commands:
          - make -f cvm.mk cvm8default17 MODE=slowdebug
      - name: Upload artifacts
        uses: actions/upload-artifact@1.0.0
        inputs:
          name: cvm8_slowdebug
          path: cvm/build/jdk8

  test_gtest_hotspot17:
    name: Test gtest hotspot17
    image: hub.byted.org/compile/bytedance.lang.buildjdk17.multiarch:9801f8057d487c1cb6914f68a9257bdc
    timeout: 30
    depends: [build_cvm8_release]
    steps:
      - name: Install CVM8
        uses: actions/download-artifact@1.0.0
        inputs:
          name: cvm8_release
          path: ./cvm/build/
      - name: Run
        commands:
          - make -f cvm.mk test_gtest_hotspot17 MODE=release SKIP_BUILD=false

  test_jtreg8_jdk_tier1:
    name: Test :jdk_tier1
    image: hub.byted.org/compile/bytedance.lang.buildjdk17.multiarch:9801f8057d487c1cb6914f68a9257bdc
    timeout: 30
    depends: [build_cvm8_release]
    steps:
      - name: Install CVM8
        uses: actions/download-artifact@1.0.0
        inputs:
          name: cvm8_release
          path: ./cvm/build/
      - name: Run
        commands:
          - make -f cvm.mk test_jtreg8_jdk_tier1 MODE=release SKIP_BUILD=true

  test_jtreg8_langtools:
    name: Test :langtools
    image: hub.byted.org/compile/bytedance.lang.buildjdk17.multiarch:9801f8057d487c1cb6914f68a9257bdc
    timeout: 30
    depends: [build_cvm8_release]
    steps:
      - name: Install CVM8
        uses: actions/download-artifact@1.0.0
        inputs:
          name: cvm8_release
          path: ./cvm/build/
      - name: Run
        commands:
          - make -f cvm.mk test_jtreg8_langtools MODE=release SKIP_BUILD=true

  test_jtreg8_hotspot8:
    name: Test hotspot8 sanity
    depends: [build_cvm8_release]
    runs-on:
      spec: m1.2xlarge
      env: online
    image: hub.byted.org/compile/bytedance.lang.buildjdk17.multiarch:9801f8057d487c1cb6914f68a9257bdc
    timeout: 30
    steps:
      - name: Install CVM8
        uses: actions/download-artifact@1.0.0
        inputs:
          name: cvm8_release
          path: ./cvm/build/
      - name: Run
        commands:
          - make -f cvm.mk test_jtreg8_hotspot8 MODE=release SKIP_BUILD=true

  test_jtreg8_cvm8:
    name: Test cvm8
    depends: [build_cvm8_release]
    runs-on:
      spec: m1.2xlarge
      env: online
    image: hub.byted.org/compile/bytedance.lang.buildjdk17.multiarch:9801f8057d487c1cb6914f68a9257bdc
    timeout: 30
    steps:
      - name: Install CVM8
        uses: actions/download-artifact@1.0.0
        inputs:
          name: cvm8_release
          path: ./cvm/build/
      - name: Run
        commands:
          - make -f cvm.mk test_jtreg8_cvm8 MODE=release SKIP_BUILD=true

  specjbb:
    name: Test SPECjbb2015
    image: hub.byted.org/compile/bytedance.lang.buildjdk17.multiarch:9801f8057d487c1cb6914f68a9257bdc
    timeout: 300
    depends: [build_cvm8_release]
    steps:
      - name: Install CVM8
        uses: actions/download-artifact@1.0.0
        inputs:
          name: cvm8_release
          path: ./cvm/build/
      - name: Setup bvc
        uses: actions/setup-bvc
      - name: Run SPECjbb2015
        commands:
          - bvc clone sys/byteopenjdk/specjbb
          - cd specjbb
          - ../cvm/build/jdk8/bin/java -Dspecjbb.controller.type=PRESET -Dspecjbb.controller.preset.ir=10000  -Dspecjbb.controller.rtcurve.start=0.4 -Dspecjbb.controller.rtcurve.step=0.2 -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:gc.log -jar specjbb2015.jar -m COMPOSITE 2>composite.log | tee composite.out
          - grep "RUN RESULT" composite.out
